### ISSUE TITLE
AnimatorProxy is missing removeListener(AnimationListener)

### ISSUE THREAD

**Issue by marlonrichert** [jouni/Animator#6] opened 2011-10-05 12:13 UTC
AnimatorProxy needs a removeListener(AnimationListener) method. Plus, as AnimatorProxy is a descendant of Component, AnimationListener needs to extend the Component.Listener interface, so it can be passed to Component.removeListener(Component.Listener).

**Comment by jouni** [comment] 2011-10-28 05:30
Duplicate of #1

**Closed as completed by jouni** 2011-10-28 05:30 UTC
Labels: Feature, Duplicate

**Comment by marlonrichert** [comment] 2011-10-28 06:01
Good to see I had already [discussed this with you](https://github.com/jounikoivuviita/Animator/issues/1), but too bad I failed to remember that! Oops! :P

**Comment by jouni** [comment] 2011-10-28 06:07
Heh, no stress.

This issue was actually added by @tehapo long ago before you had created this issue (I merged the issues from an old repo to this new one).
